### ISSUE TITLE
Include the ICU license text

### ISSUE THREAD

**Issue by hegjon** [alerque/cldr-lua#5]
During the Fedora package review, we are missing the ICU license text for the unicode data.

See https://bugzilla.redhat.com/show_bug.cgi?id=2142653#c4 for more details.

**Comment by alerque** [comment]
Roger that.

I assume just including it in the repository will be sufficient, attempting to get `luarocks install` it put it somewhere sensible is not necessary right? It's pretty hard to do the latter anyway.

**Comment by alerque** [comment]
Looking upstream they seem to have dropped the redundant naming and are sticking to "Unicode License" instead of mixing that with the "also known as ICU Licens". I'm just going to follow suit.

**Comment by alerque** [comment]
Released in v0.3.0 (minor version bump not just patch because I updated the data to CLDR 42 as well).

**Comment by hegjon** [comment]
Thanks including it in the git repo is enough, since I'm using the tarball made from a git tag.
